title: "Fluxo Diário"
description: "Reflexões e ideias sobre produtividade, foco e tecnologia no dia a dia."
url: "https://fluxodiario.netlify.app" # atualize após o primeiro deploy
baseurl: ""
author: GitHub User
email: your-email@domain.com

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

remote_theme: aterenin/minima-reboot

permalink: /:categories/:year/:month/:day/:title/

header_pages:
  - about.md
  - posts.md

paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
