title: "Fluxo Diário"
description: "Reflexões e ideias sobre produtividade, foco e tecnologia no dia a dia."
url: "https://SEU-SITE.netlify.app" # atualize após o primeiro deploy
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: aterenin/minima-reboot

# Opções úteis
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
